### ISSUE TITLE
Twitter Api Research

### ISSUE THREAD

**Issue by SasheVuchkov** [SasheVuchkov/nextjs-crowd#1]
The main purpose of our app is to monitor Twitter and look out for users who mention the reactjs framework Next.js.

So we need to use the Twitter API to fetch all recent tweets. 

At first, the app will present to the visitor daily stats. That means we need all the recent tweets between 00:01 AM to 23:59 PM of the current day.   

The end goal of this task is to:

- Find out how to fetch tweets for a given period
- Find out what's the maximum number of tweets we can fetch at once
- Find out how to paginate the results
- Find out how to fetch all the relevant information:
-- Tweet's data (text, id, timestamp, likes, retweets, replies, quotes, other fields if needed)
-- Tweet Author's data (name, username, id, description, followers, following, other fields if needed)

**Comment by Chinwendu20** [comment]
-  My idea is that we can use a cronjob to fetch tweets periodically
- We would be streaming tweets and so we would receive data for tweets related to our query as it is available (in real time).
- We can paginate results using query parameters on our API  endpoints
- We can use the 'public metric' request parameter to get all of these info
