### ISSUE TITLE
Twitter API: Map the raw data to internal entity types

### ISSUE THREAD

**Issue by SasheVuchkov** [SasheVuchkov/nextjs-crowd#3]
The Twitter API responses are complex JSON objects, so we need to split that data into smaller objects. 

Right now we have: 

`export type Tweet = {
    id: string,
    author_id: string,
    text: string,
    created_at: string,
    attachments?: {
        media_keys: string[]
    },
    public_metrics: TweetPublicMetrics;
    user?: User,
}`

`export type User = {
    id: string,
    name: string,
    username: string,
    url: string,
    profile_image_url: string,
    description: string,
    created_at: string,
    verified: boolean,
    public_metrics: UserPublicMetrics,
    entities: {
        [key: string]: Record<string, Entity[]>,
    },
}`

We need a function that accepts the raw JSON response and maps its data to arrays of these types.

It returns a map in the form of: 

`{
 tweets: Tweet[],
 users: User[]
}`

We should export the function from './repos/twitter.ts'

**Comment by SasheVuchkov** [comment]
I think we should rid of the nested objects in our types because the Redis JSON module doesn't support them...

We will level up the public metrics and the media keys, and we will JSON.stringify the entities fields because they are really complex object we cannot flatten.

**Comment by Chinwendu20** [comment]
Are you saying we should remove the public metrics and media key from our tweet data?

**Comment by SasheVuchkov** [comment]
No, no -  not removing them. Just flatten the structure by getting the props of the nested objects and making them props of the top-level object, because Redis Json Module doesn't support nested objects as far as I know
