### ISSUE TITLE
Redis: Create a factory function that creates a Redis Client

### ISSUE THREAD

**Issue by SasheVuchkov** [SasheVuchkov/nextjs-crowd#5]
Follow the Redis Om documentation and write an async function that creates a Redis client and opens a connection.

The function needs to be exported from a file named "./dbs/redis/client.ts" or "./dbs/redis/redis.js" in a folder "./dbs.

PS.  We must create one client only no matter how often the function is imported.

**Comment by Chinwendu20** [comment]
[Link to the task](https://github.com/SasheVuchkov/nextjs-crowd/blob/adding-features/lib/dbs/redis/client.ts)

@SasheVuchkov Kindly help review

**Comment by SasheVuchkov** [comment]
Good job :)
