### ISSUE TITLE
Twitter Api: Find a way to fetch tweets periodically

### ISSUE THREAD

**Issue by SasheVuchkov** [SasheVuchkov/nextjs-crowd#8]
Because the app shows data we haven't beforehand, we need to fetch new tweets periodically. Let's say every 10 mins. 

Create a utility function that will periodically invoke a previously created fetch function. It must fetch tweets in batches using the Twitter API's capabilities for result pagination. 

Because of API usage limitations, you must fetch no more than 500 tweets at a time.

**Comment by Chinwendu20** [comment]
We could use a cronjob for this. What do you think?

**Comment by SasheVuchkov** [comment]
Yup, cronjob sounds good
